### ISSUE TITLE
Markdowneditor does not show up

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/markdowneditor#2]
After enabling the module and going to Configuration > Content Authoring > BUEditor (admin/config/config/content/bueditor) the markdown editor is not listed BUEditor's settings.

**Comment by herbdool** [comment]
Do you feel like adopting this module? When I first posted it I believe it worked but that was a while ago and I'm not using it.

**Comment by alanmels** [comment]
I doubt I will have time for this one soon, but eventually we will need this module for one of customer projects, so you could add me as co-maintainer.

**Comment by herbdool** [comment]
@alanmels I've added you as maintainer. Even though I had ported it I hadn't added myself as a maintainer.

**Comment by alanmels** [comment]
@herbdool Thanks. I will take a closer look at the port some day. Meanwhile, I don't seem to have admin rights over the module, so please also adjust the permissions if you can.

**Comment by herbdool** [comment]
I've given you rights to maintain and write to the project.
