### ISSUE TITLE
Errors occurred while packaging this project on Backdrop CMS.

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/markdowneditor#3]
> Errors occurred while packaging this project on Backdrop CMS.
> Check the recent GitHub hook requests at https://github.com/markdowneditor/settings/hooks for more information.
> X-GitHub-Delivery: 75b1b9b0-297b-11eb-9def-6e52644cce5c
> 
> You may delete this error log by editing this release on GitHub. A separate log is kept in the hook request history.
> 
> 
> After resolving the below errors, create another release to try packaging again.
> 
> 
> Reported errors:
> The project node could not be created on BackdropCMS.org because no "type" property was specified in the project .info file. Info file contents: Array
> (
>     [name] => Markdown Editor for BUEditor
>     [description] => Provides a toolbar for writing Markdown syntax with BUEditor.
>     [backdrop] => 1.x
>     [package] => Content authoring
>     [dependencies] => Array
>         (
>             [0] => bueditor
>         )
> 
>     [recommends] => Array
>         (
>             [0] => ajax_markup
>             [1] => markdown
>         )
> 
>     [version] => 1.x-1.x
> )
>

**Comment by indigoxela** [comment]
Additionally to adding the required "type = module", you should also use tags in this form: `1.x-1.0.0`

**Comment by alanmels** [comment]
But why in that specific form? Can't we use just `1.x-1.0`?

**Comment by indigoxela** [comment]
> Can't we use just

You obviously can. :wink: But semver is recommended https://semver.org/

**Comment by alanmels** [comment]
> > Can't we use just
> 
> You obviously can. 😉 But semver is recommended https://semver.org/

Good read. From now on I will switch to semver. Thanks for the link!
